# -*- coding: utf-8 -*-
"""Shared types for retrieval integration."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class SourceChunk:
    """One normalized chunk from source data."""

    chunk_id: str
    user_id: str
    session_name: str
    channel_prefix: str
    file_path: str
    role: str
    chunk_text: str
    preview: str
    start_pos: int = 0
    end_pos: int = 0
    updated_at: int = 0
    content_hash: str = ""


@dataclass
class KeywordHit:
    chunk_id: str
    score: float
    snippet: str


@dataclass
class VectorHit:
    chunk_id: str
    score: float


@dataclass
class SearchHit:
    chunk_id: str
    user_id: str
    session_name: str
    channel_prefix: str
    file_path: str
    preview: str
    role: str
    keyword_score: float = 0.0
    vector_score: float = 0.0
    final_score: float = 0.0
    matched_by: List[str] = field(default_factory=list)


@dataclass
class SearchSessionHit:
    """Top hit grouped by session."""

    user_id: str
    session_name: str
    channel_prefix: str
    file_path: str
    score: float
    preview: str
    role: str
    matched_by: List[str]
    source_chunk_id: str
    metadata: Dict[str, str] = field(default_factory=dict)


@dataclass
class ChunkSpan:
    """A text span generated by chunking."""

    start: int
    end: int
    text: str


@dataclass
class SessionMessageRecord:
    """One normalized message-like record extracted from session json."""

    role: str
    text: str
    message_index: int


@dataclass
class SessionDocument:
    """Parsed chat session file."""

    file_path: str
    user_id: str
    session_name: str
    channel_prefix: str
    updated_at: int
    updated_at_text: str
    messages: List[SessionMessageRecord] = field(default_factory=list)


@dataclass
class FileFingerprint:
    """Filesystem signature for incremental indexing."""

    file_path: str
    mtime: float
    size: int


@dataclass
class IndexStats:
    """Stats for one index sync round."""

    scanned_files: int = 0
    indexed_files: int = 0
    skipped_files: int = 0
    deleted_files: int = 0
    chunks_written: int = 0
    errors: int = 0
    last_error: str = ""


@dataclass
class SearchResponse:
    """Search response payload returned by engine."""

    query: str
    limit: int
    total_sessions: int
    session_hits: List[SearchSessionHit] = field(default_factory=list)
    elapsed_ms: int = 0


@dataclass
class EngineStatus:
    """Current retrieval engine status."""

    ready: bool
    indexing: bool
    last_indexed_at: str
    embedder: str
    db_path: str
    chunks: int = 0
    files: int = 0
    watcher_running: bool = False
    last_error: str = ""
    extra: Dict[str, str] = field(default_factory=dict)


@dataclass
class EmbeddingConfig:
    """Embedding backend config."""

    provider: str = "sentence_transformers"
    model: str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    base_url: str = ""
    api_key: str = ""
    dimensions: Optional[int] = None
    device: str = "cpu"
    batch_size: int = 32
    normalize: bool = True
